AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - config/initializers/sequel_schema_parser.rb
Rails:
  Enabled: true
Rails/DynamicFindBy:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Lint/Debugger:
  Enabled: false
Naming/PredicateName:
  Enabled: false
