AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - config/initializers/sequel_schema_parser.rb
Rails:
  Enabled: true
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Lint/Debugger:
  Enabled: false
