# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: mt-test
  host: localhost
  username: skillstar
  pool: 5
  connections: 5


production:
  adapter: em_postgresql
  database: mt-test
  host: localhost
  username:
  pool: 5
  connections: 5
