defaults: &defaults
  adapter: postgresql
  pool: 5
  timeout: 5000
  min_messages: warning
  host: localhost
  username: <%= ENV['USER'] %>
  password: postgres

development:
  <<: *defaults
  database: adminium-development

test:
  <<: *defaults
  database: adminium-test

fixture-postgres:
  <<: *defaults
  database: adminium-fixture
