# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3c188a2898a12630390e65dbc744c714af56a536d93bbb6415087c2308f53529237998ea949fb2928836423599ccfce2da433a1938af9de85aa53b49e46110c

test:
  secret_key_base: a8944960f31fe92ebaeb34b06196f85026b76daf70e9a2c95edf9efb4b9a121c4685e55f8105029175ee876c84f4b08e1dd8c57ed3dd2c275166a863f460a0b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= Figaro.env.secret_key_base %>
